# ABOUTME: Builds the portable mosh engine libraries for native Windows ARM64.
# ABOUTME: Provides the standalone EXE build spike without running autotools.

CXX = clang++
AR = ar
ARM_MCPU ?= -mcpu=oryon-1

NM ?= llvm-nm
OBJDUMP ?= llvm-objdump

PREFIX ?= /opt/mosh-arm64
CPPFLAGS = -I. -Isrc/include -I$(PREFIX)/include -DNCURSES_STATIC -include win32/config.h.clangarm64
CXXFLAGS = -std=c++17 -O2 $(ARM_MCPU)
LDFLAGS = -L$(PREFIX)/lib

BUILD = win32/build

CRYPTO_SRCS = src/crypto/ocb_internal.cc src/crypto/base64.cc src/crypto/crypto.cc
PROTO_SRCS = src/protobufs/userinput.pb.cc src/protobufs/hostinput.pb.cc src/protobufs/transportinstruction.pb.cc
UTIL_SRCS = src/util/locale_utils.cc src/util/swrite.cc src/util/select.cc src/util/timestamp.cc src/util/pty_compat.cc
TERMINAL_SRCS = src/terminal/parseraction.cc src/terminal/parser.cc src/terminal/parserstate.cc src/terminal/terminal.cc src/terminal/terminaldispatcher.cc src/terminal/terminaldisplay.cc src/terminal/terminaldisplayinit.cc src/terminal/terminalframebuffer.cc src/terminal/terminalfunctions.cc src/terminal/terminaluserinput.cc
STATESYNC_SRCS = src/statesync/completeterminal.cc src/statesync/user.cc

CRYPTO_OBJS = $(patsubst %.cc,$(BUILD)/%.o,$(CRYPTO_SRCS))
PROTO_OBJS = $(patsubst %.cc,$(BUILD)/%.o,$(PROTO_SRCS))
UTIL_OBJS = $(patsubst %.cc,$(BUILD)/%.o,$(UTIL_SRCS))
TERMINAL_OBJS = $(patsubst %.cc,$(BUILD)/%.o,$(TERMINAL_SRCS))
STATESYNC_OBJS = $(patsubst %.cc,$(BUILD)/%.o,$(STATESYNC_SRCS))

LIBS = src/crypto/libmoshcrypto.a src/protobufs/libmoshprotos.a src/util/libmoshutil.a src/terminal/libmoshterminal.a src/statesync/libmoshstatesync.a

.PHONY: all clean protobufs check config

all: $(LIBS) mosh.exe

check: all
	test -f mosh.exe
	if $(NM) -u mosh.exe | grep -Eq "__cxa|_Z|_Unwind"; then exit 1; fi
	$(OBJDUMP) -p mosh.exe | grep -i "DLL Name:" || true
	if $(OBJDUMP) -p mosh.exe | grep -Eiq "libstdc\+\+|libc\+\+|libgcc|libunwind|protobuf|abseil|absl"; then \
	  echo "ERROR: mosh.exe dynamically imports a C++/protobuf runtime DLL"; exit 1; fi

config: src/include/config.h

src/include/config.h: win32/config.h.clangarm64
	cp $< $@

protobufs: src/protobufs/userinput.pb.h src/protobufs/hostinput.pb.h src/protobufs/transportinstruction.pb.h

src/protobufs/%.pb.h src/protobufs/%.pb.cc: src/protobufs/%.proto
	protoc --cpp_out=src/protobufs -Isrc/protobufs $<

src/crypto/libmoshcrypto.a: $(CRYPTO_OBJS)
	$(AR) rcs $@ $^

src/protobufs/libmoshprotos.a: protobufs $(PROTO_OBJS)
	$(AR) rcs $@ $(PROTO_OBJS)

src/util/libmoshutil.a: $(UTIL_OBJS)
	$(AR) rcs $@ $^

src/terminal/libmoshterminal.a: $(TERMINAL_OBJS)
	$(AR) rcs $@ $^

src/statesync/libmoshstatesync.a: $(STATESYNC_OBJS)
	$(AR) rcs $@ $^

mosh.exe: win32/spike.cc src/crypto/libmoshcrypto.a src/protobufs/libmoshprotos.a src/util/libmoshutil.a src/terminal/libmoshterminal.a src/statesync/libmoshstatesync.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ win32/spike.cc -Wl,--start-group src/crypto/libmoshcrypto.a -Wl,-Bstatic $(shell pkg-config --libs --static protobuf) -Wl,-Bdynamic src/protobufs/libmoshprotos.a src/util/libmoshutil.a src/terminal/libmoshterminal.a src/statesync/libmoshstatesync.a -Wl,--end-group $(LDFLAGS) -lcrypto -lz -ltinfo -lws2_32 -luser32 -static-libstdc++ -static-libgcc

$(BUILD)/%.o: %.cc src/include/config.h
	@mkdir -p $(dir $@)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -rf $(BUILD) $(LIBS) mosh.exe src/protobufs/*.pb.cc src/protobufs/*.pb.h src/include/config.h
